### ISSUE TITLE
divio-cli ignores docker-compose.override.yml

### ISSUE THREAD

**Issue by stefanfoulis** [divio/divio-cli#181]
The default behaviour of ``docker-compose`` is to override anything in the default ``docker-compose.yml`` file with the values from ``docker-compose.override.yml``.
https://docs.docker.com/compose/extends/#/understanding-multiple-compose-files

``divio`` cli seems to ignore the override file.

In my case I override the db container to expose the postgres port on localhost in ``docker-compose.override.yml``. Every time I run a command from divio-cli that uses the db container, it shuts it down and restarts it without the exposed port.

example ``docker-compose.yml``:

```yaml
version: "2"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ".:/app:rw"
    links:
      - "db:postgres"
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-local

  db:
    image: postgres:9.4
    volumes:
      - ".:/app:rw"
    environment:
      POSTGRES_DB: "db"
```

example ``docker-compose.override.yml``:

```yaml
version: "2"
services:
  db:
    ports:
      - "5432:5432"
```
